#kübernetesin calistigi pod üzerinde data adinda bir klösör vardir. Bu klösrün icinde yapilandirma dosyalari mevcuttur.
#bu data klösrünü olusturdugumuz pod icine baglamask istedigimizde karsimiza HostPath cikiyor.
#ama hostpath volume kullanimi cok fazla güvenlik problemi yasamaktadir.Producktion ortaminda kullanilmmasi önerilmektedir.
apiVersion: v1
kind: Pod
metadata:
  name: podvolumehostpath
spec:
  containers:
  - name: hostpathcontainer
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: directory-vol
      mountPath: /usr/share/nginx/html
    - name: dircreate-vol
      mountPath: /storage
    - name: file-vol
      mountPath: /tmp/config.xml
  volumes:
  - name: directory-vol
    hostPath:
      path: /tmp/vol/html
      type: Directory
  - name: dircreate-vol
    hostPath:
      path: /tmp/vol/storage
      type: DirectoryOrCreate
  - name: file-vol
    hostPath:
      path: /tmp/vol/config.xml
      type: FileOrCreate
