apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-standard
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standart_LRS
  kind: managed
volumeBindingMode: WaitForFirstConsumer