apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pervolume001-mysql-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeMode: Filesystem
  selector:
    matchLabels:
      type: pv001