#probe olusan podlarin calismasinin saglikli olup olmafdigini kontrol eden bir yapidir.
#Healthcheck in üctane yolu vardir bunlar : Readiness Probe, Livevess Probe, Startup Probe dir.
#Readiness Probe:Uygulamanizin hazir olup olmadigini kübernetese bildirmek amaciyla kullanilir
#livevess Probe: uygulamnin saglikli calisip calismadigini kontrol etmek amaciyla kullanilmaktadir.
#Uygulama sorunsuz bir sekilde calisyorsa, kubernete onu kendi haline birakir.
#startup Probe:ilk calistirilan Probedur. Yavas ayaga kalkan uygulamalar icin kullanilmaktadir.
#Probe ayaga kalkmadan Pod un kubernetes tarafindan ortadan kaldirilmasi önlenmis olur.Liveness Probe ile birlikte kullanilabilir.
#Probe yöntemleri ExecAction , TCPSocketAction, HTTPGetAction
#ExecAction , Pod icerisinde komut calistirmak icin kullanilmaktadir.Böylece gerekli test islemi yapilir.
#Komut calistirildiktan sonra dönen deger 0 ise uygulama saglikli bir sekilde calisiyor demektir.
#farkli bir deger dönerse uygulamanin crash oldugu dusunulerek gerekli rstart islemi yaoilir
#TcpSocketAction : yaml dosyasinda belirtilen tcp port bilgiisni icimde ulasaliilir olup olamdigini kontrol etmek icin kullanilmaktadir.
#HTTGetAction: http adresinie ve portuna sorunsuz bir sekilde erisip erisilmedigini kontrol etmek amaciyla kullanilmaktadir.
apiVersion: v1
kind: Pod
metadata:
  name: liveness-command-exec
spec:
  containers:
  - name: liveness-command-exec
    image: nginx
    ports:
        - containerPort: 80
    livenessProbe:
      exec:
        command:
        - cat
        - /usr/share/nginx/html/index.html
      initialDelaySeconds: 2
      periodSeconds: 2
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: liveness-http
spec: 
  containers: 
  - name: liveness-http
    image: nginx 
    ports: 
        - containerPort: 80 
    livenessProbe: 
      httpGet: 
        path: /index.html
        port: 80
      initialDelaySeconds: 2 #Default 0 
      periodSeconds: 2 #Default 10 <
      timeoutSeconds: 1 #Default 1 
      successThreshold: 1 #Default 1 
      failureThreshold: 3 #Default 3
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: liveness-tcpsocket
spec: 
  containers: 
  - name: liveness-tcpsocket
    image: nginx 
    ports: 
        - containerPort: 80 
    livenessProbe: 
      tcpSocket:
        port: 80
      initialDelaySeconds: 2 #Default 0 
      periodSeconds: 2 #Default 10 
      timeoutSeconds: 1 #Default 1 
      successThreshold: 1 #Default 1 
      failureThreshold: 3 #Default 3
      
