#podlari replicaset nesnesiyle calistitiryoruz.
#deployment üc kisimdan olusur bunlar: replicaset yönetimi , rolling update, rollback
#Replica set uygulamanin ölceklendirilmesi ve kesintiisiz calsimasini saglar.Eger bir pod duserse onu tekrardan olusturur.
#Rolling update güncel versioynu kullanima alinirken kesintisiz bir sekilde uygulamnin calismasini saglar.
#Rollback guncelleme eger istenilen sonucu vermezse eski sürüme geri dönme islemidir
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: nginx
spec:
  replicas: 5
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: web-deploy-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: web-deploy-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80