apiVersion: v1
kind: Pod
metadata:
  name: label-web-pod
  labels:
    env: production
    tier: frontend
spec:
  containers:
    - name: web-container
      image: nginx
      ports:
        - containerPort: 80