apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: cpu-men-demo
spec:
  containers:
  - name: cpu-container
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"     